apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-user-pvc
  labels:
    app: postgres-user
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard