apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-order-pvc
  labels:
    app: postgres-order
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard