apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  labels:
    app: product-service
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "kubernetes"
  
  # Application Name
  SPRING_APPLICATION_NAME: "product-service"
  
  # Server Configuration
  SERVER_PORT: "8082"
  
  # Database Configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-product:5432/product_db"
  SPRING_DATASOURCE_USERNAME: "ecommerce"
  
  # JPA Configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  
  # Actuator Configuration
  MANAGEMENT_ENDPOINTS_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_HEALTH_SHOW_DETAILS: "always"
  # Metrics Prometheus 
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  
  # Swagger/OpenAPI Configuration
  SPRINGDOC_API_DOCS_PATH: "/api-docs"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
  SPRINGDOC_OPERATIONS_SORTER: "method"
  SPRINGDOC_TAGS_SORTER: "alpha"