apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  labels:
    app: user-service
type: Opaque
data:
  # I valori devono essere in BASE64
  SPRING_DATASOURCE_PASSWORD: ZWNvbW1lcmNlMTIz  # ecommerce123
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LW11c3QtYmUtYXQtbGVhc3QtMjU2LWJpdHMtbG9uZy1mb3ItaHMyNTYtYWxnb3JpdGhtLWNoYW5nZS1pbi1wcm9kdWN0aW9u  # your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm-change-in-production