apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    app: user-service
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "kubernetes"
  
  # Application Name
  SPRING_APPLICATION_NAME: "user-service"
  
  # Database Configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-user:5432/user_db"
  SPRING_DATASOURCE_USERNAME: "ecommerce"
  
  # JPA Configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  
  # SQL Init Configuration
  SPRING_SQL_INIT_MODE: "never"
  
  # Server Configuration
  SERVER_PORT: "8081"
  
  # Actuator Configuration
  MANAGEMENT_ENDPOINTS_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_HEALTH_SHOW_DETAILS: "always"
  # Metrics Prometheus 
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  
  # Swagger/OpenAPI Configuration
  SPRINGDOC_API_DOCS_PATH: "/api-docs"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
  
  # JWT Configuration
  JWT_EXPIRATION: "86400000"